language: php
sudo: required
php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
before_script:
    - composer install
script: phpunit --configuration phpunit.xml --coverage-text
