SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
CREATE DATABASE IF NOT EXISTS CLASSROOMCONNECT DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE CLASSROOMCONNECT;

CREATE TABLE CLASSES (
  class_id int(10) UNSIGNED NOT NULL,
  time_created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  class_name varchar(60) NOT NULL,
  user_id int(11) NOT NULL,
  poll_id int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE MARKERS (
  id int(10) UNSIGNED NOT NULL,
  time_created timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  marker_id int(11) NOT NULL,
  comments varchar(1000) NOT NULL,
  email varchar(100) NOT NULL,
  class_id int(10) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE POLL (
  id int(10) UNSIGNED NOT NULL,
  marker_id int(10) UNSIGNED NOT NULL,
  email varchar(100) NOT NULL,
  class_id int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USERS (
  user_id int(10) UNSIGNED NOT NULL,
  first_name varchar(30) NOT NULL,
  last_name varchar(30) NOT NULL,
  email varchar(60) NOT NULL,
  user_password varchar(30) NOT NULL,
  poll_id int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE CLASSES
  ADD PRIMARY KEY (class_id);

ALTER TABLE MARKERS
  ADD PRIMARY KEY (id),
  ADD UNIQUE KEY email (email);

ALTER TABLE POLL
  ADD PRIMARY KEY (id),
  ADD UNIQUE KEY email (email);

ALTER TABLE USERS
  ADD PRIMARY KEY (user_id),
  ADD UNIQUE KEY email (email);


ALTER TABLE CLASSES
  MODIFY class_id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE MARKERS
  MODIFY id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE POLL
  MODIFY id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE USERS
  MODIFY user_id int(10) UNSIGNED NOT NULL AUTO_INCREMENT;